### ISSUE TITLE
TypeError: 'QVariant' object is not subscriptable

### ISSUE THREAD

**Issue by marklit** [skeenp/QGIS3-getWKT#12]
This error came up when trying to install your plugin.

```
Couldn't load plugin 'QGIS3-getWKT' due to an error when calling its classFactory() method 

TypeError: 'QVariant' object is not subscriptable 
Traceback (most recent call last):
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/mark/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/QGIS3-getWKT/__init__.py", line 32, in classFactory
    return getwkt3(iface)
  File "/Users/mark/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/QGIS3-getWKT/getwkt3.py", line 58, in __init__
    locale = QSettings().value('locale/userLocale')[0:2]
TypeError: 'QVariant' object is not subscriptable
```

Python version: 3.9.5 (default, Sep 10 2021, 16:18:19) [Clang 12.0.5 (clang-1205.0.22.11)] 
QGIS version: 3.34.3-Prizren Prizren, 47373234acd

**Comment by skeenp** [comment]
I have just deployed an update to hopefully fix the issue. Will provide an update when the update is approved and live.

**Comment by skeenp** [comment]
Update is now live, hope this version rectifies your issue. If not please reopen the issue or create a new one and I'll take another look.
